### ISSUE TITLE
You can do standard deviation pretty easily with sum^2

### ISSUE THREAD

**Issue by ashtul** [cryptorelay/redis-aggregation#1]
You can see implementation at -https://github.com/RedisTimeSeries/RedisTimeSeries/blob/7911f43e2861472565b2aa61d8e91a9c37ec6cae/src/compaction.c

**Comment by yihuang** [comment]
Cools, thanks for reminding. RedisTimeSeries is quite similar to what I have in mind, do you plan to support multiple columns? Also I think some kind of combination with Redis stream is also an interesting direction.

**Comment by yihuang** [comment]
Just port your code from RedisTimeSeries, thanks again ;D

**Comment by ashtul** [comment]
RedisTimeSeries is a combination with a tailored stream for efficiency and speed.
If you want to know more you should contact the developer @danni-m
